//! The Stable Diffusion invisible-watermark detector (roadmap plan, W1) —
//! a from-source transcription of the decode path of the open reference
//! implementation the SD pipelines call: ShieldMnt/invisible-watermark,
//! `imwatermark/maxDct.py`, class `EmbedMaxDct`, method name `dwtDct`.
//!
//! The algorithm, exactly as the reference does it (note: despite the
//! library's method name, the dwtDct decode path applies NO discrete cosine
//! transform — that only exists in the separate SVD variant):
//!
//! 1. Convert BGR→YUV as OpenCV does on uint8 (BT.601 analog matrix,
//!    rounded to u8) and take channel 1 — the U chrominance plane.
//!    (`scales = [0, 36, 36]` with a `range(2)` channel loop means only
//!    channel 1, scale 36, is ever used.)
//! 2. Crop rows and columns to multiples of 4, then take the approximation
//!    (LL) band of a one-level Haar DWT: `LL[i][j] = (a + b + c + d) / 2`
//!    over each 2×2 pixel quad.
//! 3. Walk the LL band in 4×4 blocks, row-major. Per block: find the
//!    max-|coefficient| excluding flat index 0 (first maximum wins, as
//!    `np.argmax` does), and score the block `1` if `|val| mod 36 > 18`,
//!    else `0` — the embedder quantized that coefficient to the 0.25 (bit 0)
//!    or 0.75 (bit 1) point of its scale-36 interval.
//! 4. Block k votes for payload bit `k mod wmLen`; a bit is 1 when
//!    `mean(scores) * 255 > 127` (the reference's exact threshold).
//! 5. The reference decoder refuses images with `rows * cols < 256 * 256`;
//!    so do we (`None`, not an error).
//!
//! A detection is claimed ONLY when every decoded bit equals a known Stable
//! Diffusion payload — no partial matches, no similarity scores. Payloads
//! pinned from their primary sources (2026-07-31):
//!
//! - SDXL (diffusers `pipelines/stable_diffusion_xl/watermark.py`):
//!   `WATERMARK_MESSAGE = 0b101100111110110010010000011110111011000110011110`,
//!   embedded as 48 bits via `set_watermark("bits", …)`.
//! - SD v1 (CompVis/stable-diffusion `scripts/txt2img.py`):
//!   `wm = "StableDiffusionV1"` embedded as UTF-8 bytes via
//!   `np.unpackbits` — MSB-first per byte, 136 bits.
//!
//! SD 2.x's `"SDV2"` payload is deliberately NOT probed yet: its constant
//! was not verifiable from a primary source today, and a 32-bit exact match
//! carries materially more false-positive risk — add it only with both a
//! pinned source and a measured FPR (roadmap plan Decision Log).
//!
//! Known-answer vectors live in `tests/vectors/watermark/`, generated by the
//! VERBATIM reference embedder (`scripts/gen_watermark_vectors.py`) — the
//! decoder is tested against ground truth it did not produce. False-positive
//! measurement: `cargo run -p provenance-core --example measure_fpr -- <dir>`.

use crate::layers::watermark::{DecodedImage, WatermarkDetector, WatermarkHit};

/// Quantization scale the reference uses for the U channel (`scales[1]`).
const SCALE: f64 = 36.0;

/// diffusers WATERMARK_MESSAGE — 48 bits, MSB first (`bin(x)[2:]`).
const SDXL_MESSAGE: u64 = 0b101100111110110010010000011110111011000110011110;
const SDXL_LEN: usize = 48;

/// CompVis SD v1 payload, embedded MSB-first per byte (np.unpackbits).
const SDV1_BYTES: &[u8] = b"StableDiffusionV1";

fn sdxl_bits() -> Vec<u8> {
    (0..SDXL_LEN)
        .map(|k| ((SDXL_MESSAGE >> (SDXL_LEN - 1 - k)) & 1) as u8)
        .collect()
}

fn sdv1_bits() -> Vec<u8> {
    SDV1_BYTES
        .iter()
        .flat_map(|byte| (0..8).map(move |i| (byte >> (7 - i)) & 1))
        .collect()
}

/// Steps 1–3: per-4×4-block scores in row-major order, payload-independent.
fn block_scores(image: &DecodedImage) -> Option<Vec<u8>> {
    // Reference guard: WatermarkDecoder.decode refuses r*c < 256*256.
    if image.width * image.height < 256 * 256 {
        return None;
    }
    let rows = image.height / 4 * 4;
    let cols = image.width / 4 * 4;
    if rows == 0 || cols == 0 {
        return None;
    }

    // U plane exactly as cv2.COLOR_BGR2YUV produces it on uint8 input:
    // U = -0.14713 R - 0.28886 G + 0.436 B + 128, rounded and clamped to u8
    // (the reference converts the uint8 image first, so the plane is
    // quantized before the DWT — we reproduce that quantization).
    let mut u_plane = vec![0f64; rows * cols];
    for y in 0..rows {
        for x in 0..cols {
            let p = (y * image.width + x) * 3;
            let r = image.rgb[p] as f64;
            let g = image.rgb[p + 1] as f64;
            let b = image.rgb[p + 2] as f64;
            let u = (-0.14713 * r - 0.28886 * g + 0.436 * b + 128.0).round();
            u_plane[y * cols + x] = u.clamp(0.0, 255.0);
        }
    }

    // One-level Haar DWT approximation band (pywt 'haar', even dims:
    // non-overlapping 2×2 quads, coefficient = quad sum / 2).
    let (ll_rows, ll_cols) = (rows / 2, cols / 2);
    let mut ll = vec![0f64; ll_rows * ll_cols];
    for i in 0..ll_rows {
        for j in 0..ll_cols {
            let quad = u_plane[(2 * i) * cols + 2 * j]
                + u_plane[(2 * i) * cols + 2 * j + 1]
                + u_plane[(2 * i + 1) * cols + 2 * j]
                + u_plane[(2 * i + 1) * cols + 2 * j + 1];
            ll[i * ll_cols + j] = quad / 2.0;
        }
    }

    // 4×4 blocks, row-major; per block the reference's infer_dct_matrix:
    // argmax |flat[1..]| (first max wins), score = |val| mod 36 > 18.
    let mut scores = Vec::with_capacity((ll_rows / 4) * (ll_cols / 4));
    for bi in 0..ll_rows / 4 {
        for bj in 0..ll_cols / 4 {
            let mut flat = [0f64; 16];
            for (di, row) in flat.chunks_mut(4).enumerate() {
                for (dj, cell) in row.iter_mut().enumerate() {
                    *cell = ll[(bi * 4 + di) * ll_cols + (bj * 4 + dj)];
                }
            }
            let mut best_idx = 1;
            let mut best_abs = -1.0f64;
            for (idx, coeff) in flat.iter().enumerate().skip(1) {
                if coeff.abs() > best_abs {
                    best_abs = coeff.abs();
                    best_idx = idx;
                }
            }
            let val = flat[best_idx].abs();
            scores.push(u8::from(val % SCALE > 0.5 * SCALE));
        }
    }
    if scores.is_empty() {
        None
    } else {
        Some(scores)
    }
}

/// Step 4: fold block scores into `wm_len` bit slots and threshold exactly
/// as the reference does. `None` if any slot got no votes (image too small
/// for this payload length — the reference would average an empty list).
fn vote(scores: &[u8], wm_len: usize) -> Option<Vec<u8>> {
    let mut sum = vec![0u32; wm_len];
    let mut count = vec![0u32; wm_len];
    for (num, &score) in scores.iter().enumerate() {
        sum[num % wm_len] += u32::from(score);
        count[num % wm_len] += 1;
    }
    if count.contains(&0) {
        return None;
    }
    Some(
        (0..wm_len)
            .map(|k| u8::from(sum[k] as f64 / count[k] as f64 * 255.0 > 127.0))
            .collect(),
    )
}

pub struct SdInvisibleWatermark;

impl WatermarkDetector for SdInvisibleWatermark {
    fn vendor(&self) -> &'static str {
        "stable-diffusion-invisible-watermark"
    }

    fn probe(&self, image: &DecodedImage) -> Option<WatermarkHit> {
        let scores = block_scores(image)?;
        let payloads = [
            (
                "the Stable Diffusion XL invisible watermark (48-bit dwtDct payload, \
                 decoded exactly)",
                sdxl_bits(),
            ),
            (
                "the Stable Diffusion V1 invisible watermark (136-bit dwtDct payload \
                 \"StableDiffusionV1\", decoded exactly)",
                sdv1_bits(),
            ),
        ];
        for (source, expected) in payloads {
            if vote(&scores, expected.len()).is_some_and(|bits| bits == expected) {
                return Some(WatermarkHit {
                    source: source.to_string(),
                });
            }
        }
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn payload_bit_derivations_match_numpy_conventions() {
        let sdxl = sdxl_bits();
        assert_eq!(sdxl.len(), 48);
        // bin(WATERMARK_MESSAGE)[2:] starts "10110011…"
        assert_eq!(&sdxl[..8], &[1, 0, 1, 1, 0, 0, 1, 1]);
        let sdv1 = sdv1_bits();
        assert_eq!(sdv1.len(), 136);
        // 'S' = 0x53 = 01010011, MSB first per np.unpackbits.
        assert_eq!(&sdv1[..8], &[0, 1, 0, 1, 0, 0, 1, 1]);
    }

    #[test]
    fn small_images_are_refused_like_the_reference() {
        let image = DecodedImage {
            rgb: vec![128; 255 * 255 * 3],
            width: 255,
            height: 255,
        };
        assert!(block_scores(&image).is_none());
        assert!(SdInvisibleWatermark.probe(&image).is_none());
    }
}
