//! PDQ known-answer tests (registry plan, G1): the Rust transcription in
//! `layers/pdq.rs` must match the compiled reference implementation
//! bit-for-bit (hash) and exactly (quality) on the committed PNG vectors.
//! Expectations generated by `py scripts/gen_pdq_kats.py` (the `pdqhash`
//! wrapper builds Meta's reference C++ — ground truth this code did not
//! produce).

use std::path::PathBuf;

use provenance_core::layers::pdq::{hamming, pdq_hash, PdqHash};
use provenance_core::layers::watermark::DecodedImage;

fn vectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/vectors")
}

fn load(rel: &str) -> DecodedImage {
    let decoded = image::open(vectors_dir().join(rel))
        .expect("read KAT vector")
        .to_rgb8();
    let (width, height) = (decoded.width() as usize, decoded.height() as usize);
    DecodedImage {
        rgb: decoded.into_raw(),
        width,
        height,
    }
}

fn hex(hash: &PdqHash) -> String {
    hash.bits.iter().map(|b| format!("{b:02x}")).collect()
}

#[test]
fn every_kat_matches_the_reference_bit_for_bit() {
    let tsv = std::fs::read_to_string(vectors_dir().join("pdq/kats.tsv")).expect("read kats.tsv");
    let mut checked = 0;
    for line in tsv.lines().skip(1).filter(|l| !l.trim().is_empty()) {
        let mut cols = line.split('\t');
        let file = cols.next().expect("file column");
        let expected_hex = cols.next().expect("hash column");
        let expected_quality: u8 = cols.next().expect("quality column").parse().unwrap();

        let hash = pdq_hash(&load(file)).expect("hash computes");
        assert_eq!(
            hex(&hash),
            expected_hex,
            "{file}: hash differs from the reference implementation"
        );
        assert_eq!(hash.quality, expected_quality, "{file}: quality differs");
        checked += 1;
    }
    assert!(checked >= 5, "kats.tsv must list the full vector set");
}

#[test]
fn watermarking_barely_moves_the_hash_but_different_content_is_far() {
    // The property the registry rides on, demonstrated with committed
    // vectors: an invisible watermark perturbs the hash by a few bits,
    // different photographs disagree on roughly half the bits.
    let wm = pdq_hash(&load("watermark/bzh/watermarked.png")).unwrap();
    let clean_twin = pdq_hash(&load("watermark/bzh/not_watermarked.png")).unwrap();
    let other = pdq_hash(&load("watermark/clean_base.png")).unwrap();

    let twin_distance = hamming(&wm, &clean_twin);
    let cross_distance = hamming(&wm, &other);
    assert!(
        twin_distance <= 16,
        "same content ± watermark should be near: got {twin_distance}"
    );
    assert!(
        cross_distance >= 70,
        "different content should be far: got {cross_distance}"
    );
}
